name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Linting with Go ${{ matrix.gov }} on ${{ matrix.os}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        gov: ["1.24"]
    steps:
      - uses: actions/checkout@v5
      
      - name: Set up Go ${{ matrix.gov }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.gov }}
          cache: true

      # Install required packages including git
      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates git
          sudo update-ca-certificates
  
      - name: Run lint
        run: make lint
