name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Run tests with Go ${{ matrix.gov }} on ${{ matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        gov: ["1.26"]

    steps:
      - uses: actions/checkout@v5
      
      - name: Set up Go ${{ matrix.gov }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.gov }}
          cache: true
        id: go

      # Install required packages including git
      - name: Install required packages
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates git
          sudo update-ca-certificates

      - name: Get dependencies
        run: |
          git config --global http.sslVerify true
          go mod download
        
      - name: Run offline test suite
        run: make test
